### ISSUE TITLE
Pagination based data table does not update when pagination links clicked

### ISSUE THREAD

**Issue by ThorntonStuart** [reactjs/express-react-views#101]
I am building an app based on the [express-react-views][1] dynamic example to use React as my Express templating engine. Currently I am using [reactable][2] to create data tables, however the pagination feature built in to this plugin and several others (react-paginate, react-data-components) that I have tried with this app do not update/re-render the table component with the requested data when pagination links are clicked.

In the case of Reactable, the package sets the href of the pagination links to a hash, however while the link successfully renders new data in the table in standard React apps, the express-react-views app merely changes the URL and fails to update the table.

[![enter image description here][3]][3]

I have tried these packages with standard React apps which do not make use of express-react-views and had no problems.

  [1]: https://github.com/reactjs/express-react-views/tree/master/examples/dynamic
  [2]: https://github.com/glittershark/reactable
  [3]: https://i.stack.imgur.com/3Ytw3.png

**Comment by zpao** [comment]
I'm not sure if the hash gets sent to the server but you would need to handle it if so. If that's your problem here.

If you're talking about the client-side handling updates, then you're unfortunately on your own. The dynamic example is meant to be a starting point of a pattern that we don't actually support support (this project focuses on the server-side)
