### ISSUE TITLE
How to use css in 'express-react-views'?

### ISSUE THREAD

**Issue by budlover** [reactjs/express-react-views#102]
Basically I wan to render table: https://github.com/react-component/table

But looks like the table is no aligned, so I wan to use a css. But how to make css work in side 'express-react-views'?

**Comment by cinder92** [comment]
yo might me use a static resources

```
var express = require('express');

var app = express();

app.use('/public',express.static('public'));

app.set('views', __dirname + '/app');
app.set('view engine', 'jsx');
```

then in your root folder create a folder `public` with a (ex) `css` folder inside

/
/app
/public
   /css

then in your componente use it in this way

```
import React from 'react';

const Header = (props) => {
   return (
     <!doctype>
     <head>
         <link rel="stylesheet" href="/public/css/owl.carousel.css" />
     </head>
     <body></body>
   )
}

export default Header;
```

hope it helps 👍

**Comment by jackmead515** [comment]
I'm getting a 404 not found on the css file itself.

I have mine setup like:

`
/src
   /views
       head.jsx
       form.jsx
   /public
      /css
         index.css
`

with head.jsx like:

`<html>
        <head>
            <link rel="stylesheet" href="/public/css/index.css" />
        </head>
        <body>{this.props.children}</body>
      </html>`

and form.jsx like:

`<Head>
        <div className="login__container">
          <h1>Login</h1>
          <input type="text" placeholder="Username" />
          <input type="text" placeholder="Password" />
        </div>
      </Head>`

**Comment by zpao** [comment]
Closing since there hasn't been a response from filer in a long time. Thanks for helping out @cinder92

**Comment by alioshr** [comment]
Hello there. I know that this is old... I am using this package in order to avoid using ```pug.js``` while I am learning Node.js. I am not planning to use React in this way in the future, but I still need it right now. 

The example given above does not work, just by looking at the code. ```<!doctype>``` is not supported in ```jsx``` and, naturally you must use a single child per component, what is clearly not done on the example as well. 

Even after adjusting these things, it´s not possible to use <link> on the component. 

Could you kindly give us a working solution?

**Comment by msamgan** [comment]
naaa this doenst work..

**Comment by kratiknayak** [comment]
Thanks. This helped
