### ISSUE TITLE
can't render qr code from server

### ISSUE THREAD

**Issue by MBehtemam** [reactjs/express-react-views#122]
hi for creating qr code i using [qrcode.react](https://github.com/zpao/qrcode.react) and when rendering on client everything work well, but when i use this plugin with `express-react-views` the canvas is rendered but nothing was showed on canvas , if i ran same code on client everything works well ? does express-react-views need extra plugin for working with some client side react rendering

**Comment by zpao** [comment]
I answered your question over in https://github.com/zpao/qrcode.react/issues/40.

As for supporting client-side mounting here, it's possible but not actively supported. Take a look at the examples. Otherwise I'd also recommend taking a look at https://github.com/zeit/next.js/ which is what I would use if I were starting a new project today.
