### ISSUE TITLE
Return json result rather than rendering

### ISSUE THREAD

**Issue by tukhoi** [reactjs/express-react-views#124]
Hi,

I'm looking for a way to return back a json contain HTML string rather than render HTML directly to the request. Help is appreciate.

Thanks
Khoi

**Comment by zpao** [comment]
You could fork this and probably change [this line](https://github.com/reactjs/express-react-views/blob/91d5f43b7a73c60b6dc3a69b5492624e6a27477e/index.js#L90) to return a JSON object containing the markup instead of the markup itself.

I'm going to close out because that's outside the scope of what I want this to support. Good luck though.
