### ISSUE TITLE
Twitter Images don't shown

### ISSUE THREAD

**Issue by gnsam** [reactjs/express-react-views#60]
Hi,

I've just finished chapter number 7 and I've runned de application. I did npm start on snapkite-engine folder and gulp on my snapterest folder but when I go to broswer I don't see images, only text Waiting for public photos from Twitter...Your collection is empty.

If I try to do the same on your examples folder (ES6 version) I have the same issue.

I don't have js errors and I'm using Win 10.

Do you have any idea of which could be the problem?

Thanks.

**Comment by zpao** [comment]
I don't know what chapter 7 you are referring to, this is just an open source project. If you are referring to some class material, please consult your teacher.

My guess here as to your issue is that this project specifically is aimed at server-side rendering with client-side mounting being a non-goal (though it can be supported in some cases). So trying to hit the Twitter API doesn't work for updates because updates don't happen on server-side content.

I'm going to close because there doesn't appear to be anything actionable but let me know if I'm mistaken.
